version: '3.7'

# 컴퓨터들
services:
  my_backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/myDirectory/src
    ports:
      - 3000:3000
    env_file:
      - ./.env.docker

  my_database:
    # platform: linux/86_64
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'my_docker_project'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306
# docker-compose stop을 치면 전부 종료됨.
